spring:
  application:
    name: postgresql-example
  data:
    jpa.repositories.enabled: true
  datasource:
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://45.84.210.174:65432/2023-BFS-1-G4
    username: Fullstack_2023_1_G4
    password: 1qaz2wsx
    continueOnError: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 10
        order_updates: true
        batch_versioned_data: true